server {
	host 0.0.0.0;
	port 4242;
	client_max_body_size 1000000;
	error_page 404 ./www/404.html;
	location / {
	root ./www;
	index index.html;
	methods GET POST DELETE;
	autoindex off;
	upload_dir ./uploads;
	cgi_ext .py;
	cgi_bin /usr/bin/python3;
	}
}